### ISSUE TITLE
Where should we call server.stop in our tests?

### ISSUE THREAD

**Issue by rjmk** [dwyl/tudo#111]
Do we need to call `server.stop` per test file in our tests? Should we be stopping before or after `t.end`?

**Comment by nelsonic** [comment]
I favour calling `server.stop(cb)` each time `server.inject` is invoked so that we can still `test.only` an _individual test_ 

and I _suspect_ we have to call `t.end()` **_after**_ `server.stop(cb)` because `t.end()` signals to tape that there's nothing more to execute ... but I have not investigated this.

@rjmk are you _investigating_? :question:

**Comment by rjmk** [comment]
I'm for calling `server.stop(cb)` in each test. I'm even more for having a separate bootstrap file from the server file so we know which tests are with an actively running server and which aren't and don't need to remember `server.stop(cb)`.

`t.end()` appears to only be important for _assertions_.

**Comment by nelsonic** [comment]
Closing as we are calling `server.stop(t.end);`
