### ISSUE TITLE
Github oauth

### ISSUE THREAD

**Issue by des-des** [dwyl/tudo#147]
As a developer I would like to be able to log via github so that the app can request the issues associated with my organisation.

**Comment by nelsonic** [comment]
GitHub Auth working for dwylbot: https://github.com/dwyl/dwylbot/pull/27#issuecomment-286933419 (_in case you need a "head start"_) 👍

**Comment by des-des** [comment]
@nelsonic Thnx! Yeah we started by slimming it down to create a minimal working example, next will make it fully featured and add tests!

**Comment by Cleop** [comment]
**As a** new team member joining the repo with a limited amount of time to work on it
**I want to** establish whether the benefits of OAuth are high priority
**So that** I can decide whether to implement OAuth or not in the time I have available.

Whilst the description of this issue is valid for private organisations or editing we want to understand how high a priority this issue is for dwyl and whether the benefits it brings is substantial enough to prioritise given the 3/4 days we have available to progress the app. Our aim is to create an MVP. This is the discussion/ thought process that we've had around OAuth so far...

- Why OAuth?
To enable people to login to their github accounts
- Why do people want to login?
So that they can have more permissions?
- What can they do with permissions?
Amend/ add labels/assignees
- Is that not only people who have permissions in our repos? Will people new to dwyl have these permissions?
- Wouldn't someone want to see the description of an issue and any comments on its progress before you assigned yourself?
- Where do we end with this functionality so that we're not recreating github?

So far @shouston3 @Jbarget and I have concluded that we don't see using OAuth as an immediate priority. @nelsonic - thoughts?

**Comment by des-des** [comment]
@Cleop I think one potential problem is rate limiting.

https://developer.github.com/v3/#rate-limiting

A single app can only make a limited number of api calls. Not sure if this will be a problem for v1.

Oauth will get around this problem, as the limits will be set per user, which means the total limit will scale with the number of users

**Comment by samhstn** [comment]
It depends on how much we are able to store in postgres and how easy it will be to check if this data will need to be updated with as few number of requests as possible.

See [issue 146](https://github.com/dwyl/tudo/issues/149#issuecomment-318661428) on this

If we can detect wether there have been updates with just a couple of requests than just our 5000 requests per hour for all users should suffice (this would be just user our 1 api token for each request that comes through).

With oauth we would then get 5000 github api requests for that user per hour.

**Comment by Jbarget** [comment]
We started this project on a repo called `tudo-new` https://github.com/dwyl/tudo-new/tree/authentication, where authentication was completed apart from: e288b27f92e254dc9c0d0f75f8388e6444dbfe77

That branch then got merged into the `master` branch of this repo so history of commits for authentication is on `tudo-new`

closing as feature is complete

**Comment by Jbarget** [comment]
hard to give an Actual Time for this functionality as it was created a while back. I can take an educated guess of 1 day (+/- 0.5 days)
