### ISSUE TITLE
Persist issues to database

### ISSUE THREAD

**Issue by des-des** [dwyl/tudo#149]
As a user I would like the issue data to be saved in a database so that the app loads faster and works when github is down.

# Acceptance Criteria
- [x] Fetch repo data from Github
- [x] Fetch issue data from Github
- [x] Save data into database according to ecto schema #165

**Comment by Jbarget** [comment]
related to #165 (Postgres Schema)

**Comment by Cleop** [comment]
**As a** new team member joining the repo with a limited amount of time to work on it
**I want to** establish whether the benefits of postgres are high priority
**So that** I can decide whether to implement postgres or not in the time I have available.

Whilst the description of this issue is valid we want to understand how high a priority this issue is and whether the benefit it brings is substantial enough to prioritise given the 3/4 days we have available to progress the app. Our aim is to create an MVP. This is the discussion/ thought process that we've had around Postgres so far...

- Why do we need Postgres?
To work offline or when github is offline.
- Why do we need to go offline?
To work remotely (ie. in transit) or in cases of wifi loss. Or if github goes down.
- In order to benefit from offline working wouldn't I need to download the info in advance?
Yes, so maybe that wouldn't be helpful if you were losing wifi but could be useful in transit.
- How often will someone be knowing they're going offline (but with short period in advance so you don't work on duplicate issues and in a capacity where they can working on coding activities with wifi) and be a user stumbling across Tudo?
- What about github going down?
Whilst this may occur from time to time, is this a luxury rather than a necessity for getting the app live?

Postgres may help speed things up... how much? how much is this needed? how high priority is this? how much time will it take to implement?

So far @shouston3 @Jbarget and I have concluded that we don't see using postgres as an immediate priority.

**Comment by Jbarget** [comment]
Having discussed further Postgres would be beneficial for avoiding rate limiting from Github API (circa 255 requests to get all the information we need) and efficiently loading pages of `help-wanted` issues.

Proposed flow:

1. User arrives at Tudo homepage
2. Request sent off to postgres for page 1
3. User clicks for 2nd page of issues
4. Request sent off to postgres for page 2
etc...

This flow avoids having to go through the process of requesting all the repos within an organisation (3 requests), getting all the issues within those organisations (circa 250 requests) for every client request for a page of issues.

INSTEAD

We can set up polling for postgres using Tudo's `access_token` to run every 5 minutes (circa 3060 requests per hour) - or less often if deemed appropriate.

**Comment by nelsonic** [comment]
As discussed yesterday, the _benefits_ storing the GitHub (_issue_) data in a PostgreSQL Database are:
+ ***Redundancy***
  + **GitHub** has ("_Minor_") ***Outages*** roughly once every 2 months and **_Major_ Outages** every **6 months** where the site is "_down_" for _several_ hours for whatever reason.
![image](https://user-images.githubusercontent.com/194400/28744830-44120d4c-7461-11e7-8ca5-f9c3a276ae83.png)
  + We can _cache_ issues on client/device so they are viewable offline-first which will make working/UX in low-signal-quality areas better than GitHub.
![image](https://user-images.githubusercontent.com/194400/28746010-f40e95a2-747b-11e7-97af-56e68b7cdfc7.png)

+ ***Accountability***
  + Storing the issue comments (_and tracking revisions_) means we can systematically avoid "_scope creep_" (_when someone adds additional checklist items to acceptance criteria once the story is already being worked on! ask @katbow or @jruts about this ..._ 😖 ) 

+ ***Speed*** 
  + pages will load faster if we are caching the data in our own DB (_consistently less than [100ms](https://www.webdesignerdepot.com/2016/02/how-slow-is-too-slow-in-2016/)_)
  + faster filtering to get _precise_ data/views means our people are more time-effective.

+ ***Reduced Bandwidth*** on mobile devices
  + We can return a subset of ["Top 5" priorities](https://github.com/dwyl/tudo/issues/176) to mobile clients _without_ having to issue (_wait for_) 20 GitHub API queries before constructing/returning the reply to client.

## Can We Ask More _User-focussed_ Questions?

While it's _good_ to ask `if` something should be done, 
it's often more insightful to ask ***user-focussed*** `Why?`, `What?` & `How?` type questions:

### `Why` is "Tudo" needed by @dwyl team members, community and clients? (_identify pain point(s)_)

> Having ***One View*** of ***all*** our issues including:
+ Ordering by ***Priority*** by Default (_this is possible but not across orgs_)
+ Showing `Who` is **assigned** to something and _quickly_ seeing (_how many issues they have assigned to them and which ones are "`in-progress`", "`blocked`" or "`awaiting-review`" (_for example_) will help everyone in the team see _exactly_ what people are working on and _confirm_ that the _highest priority_ task is being worked on first and only a one task at a time (_yeah_, [_I know right..._](https://github.com/issues?utf8=%E2%9C%93&q=assignee%3Anelsonic+is%3Aopen+label%3Ain-progress) 🙄 )
+ QA/Remote team will be able to see _immediately_ when someone is "_stuck_" on an issue/bug
and will reduce "dead" time.

Simply displaying all issues in "One View", Tudo will be the _single_ biggest improvement to @dwyl's workflow/process. Caching the data in a Database will allow each person to have a _precise_/_custom_ dashboard they can glance at to keep track of what they are working on.

### `How` would caching GitHub data in a Database improve UX? 

### `What` is the _minimum_ useful data we can store in a Database that will enhance UX?

> We should extend the _acceptance criteria_ for this issue to include the fields of data from an issue that we want to store.

**Comment by Jbarget** [comment]
@nelsonic sounds good!

we've updated this issue with our schema, hoping to speak to you about https://github.com/dwyl/tudo/issues/191#issuecomment-318839733 before getting too far down the line

**Comment by Jbarget** [comment]
fixed with f19ec7b
