### ISSUE TITLE
Write Intro Copy

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#188]
- [x] Write intro copy to introduce 'help wanted'
- [x] Include links to dwyl resources for people who aren't familiar with our labels/contributing etc.

**Comment by Jbarget** [comment]
Initial pass at copy:

Help Wanted is a [dwyl](http://www.dwyl.com) product, made with ❤️ , so that you can easily contribute to open source projects.  The labels applied to each of these Github issues in the list below give a lot of information about that task so we'd recommend familiarising yourself with them [here](https://github.com/dwyl/labels). We'll be adding features over time based on your recommendations so please leave us feedback through an [issue](https://github.com/dwyl/tudo/issues/new) and apply the `enhancement` label.

**Comment by Cleop** [comment]
Great @Jbarget - a couple of little tweaks in my take on an edit - happy to go with either version though.... 👍 

Help Wanted is a [dwyl](http://www.dwyl.com) product, made with ❤️ , to allow you to easily contribute to our open source projects.  Each of the issues below requires help from someone like you. Not sure where your skills fit in or where to start? Why not [familiarise yourself with what our labels mean](https://github.com/dwyl/labels)?  If you want to learn more about how to contribute to dwyl repos, check out our [contributing guide](https://github.com/dwyl/contributing).

We'll be adding features over time based on your recommendations so please leave us feedback through an [issue](https://github.com/dwyl/tudo/issues/new) and apply the `enhancement` label.

**Comment by Jbarget** [comment]
We'll go with the below, it is a mixture between mine and @Cleop plus a bit of input from @iteles

Help Wanted is a dwyl product, made with ❤️ , so that you can easily contribute to open source projects. Each of the issues below requires help from someone like you; technical or not. 
Take a look at our [labels repo](https://github.com/dwyl/labels#labels) to familiarise yourself with what they mean and if you want to learn more about how to contribute to dwyl repos, check out our [contributing guide](https://github.com/dwyl/contributing).

We'll be adding features over time based on your recommendations so please leave us feedback through an issue and apply the `enhancement` label.

**Comment by Jbarget** [comment]
The above is a mixture between mine and @Cleop plus a bit of input from @iteles. We will go with that
