### ISSUE TITLE
Redis cloud url

### ISSUE THREAD

**Issue by jrans** [dwyl/tudo#20]
Using one from a black personal app but assume dwyl will want to set up one on heroku.
@nelsonic  @iteles ?

**Comment by nelsonic** [comment]
@jrans we have several Redis Cloud "_Test_" Urls. We've updated the Google Doc with one of them. :+1: 
Also why is the word TEST _in_ the key name? 
We prefer to use `REDISCLOUD_URL` **_everywhere**_ (to have fewer environment variables to have to keep track of) and simply never put the "_Real_" ("_production_") url in an env.json file (because its always stored by the server _running_ the app)

**Comment by nelsonic** [comment]
The new test url is in the env.json Google Doc: https://docs.google.com/document/d/1uztGvSE8nxjQwJtCorQUiNM9irjIoomhFuhLfghDC0o

closing issue.
