### ISSUE TITLE
Desktop / Mobile view - which information is useful/necessary

### ISSUE THREAD

**Issue by Cleop** [dwyl/tudo#203]
**This is the current desktop display:**

![image](https://user-images.githubusercontent.com/16775804/28880019-9f0414c4-779b-11e7-8420-43adefdc38b1.png)

**We are currently displaying:**

- repo name
- issue title
- labels
- assignee (s)
- No of comments

Of these elements the following click through to links on github:
- issue title and no. of comments both go to the issue's page

To do?
- repo name -> repo page?
- assignee -> assignee's profile?

**We could also display:**
- Created at date
- Updated at date

**Questions:**
- Do we want to add or remove any fields from desktop?
- Do we want to remove an fields from mobile only?

Mobile design may either be a 'card' type design or a simplified version of the table.

**Comment by iteles** [comment]
**Desktop**:
+ I would add:
  + Last updated date for the MVP
  + In future I think that 'last updated author' would be an interesting one to add but let's let that be a request
+ I wouldn't have thought to add number of comments but I guess it does show some measure of popularity!

**Mobile**:
+ I would still add last updated time
+ Remove:
  + Assignee (from display, not from future filtering capabilities)
  + No of comments (this should also give us a little insight into whether this is an interesting measure to people - i.e. if they use both desktop and mobile, they might 'miss' this feature)

'cards' might make more sense on mobile, can we please open a separate issue for card styling and time estimate it so that we can determine the impact of choosing that route for MVP?

**Comment by Jbarget** [comment]
Just a note that the idea of showing the `comments` was the thought that it would promote discovery and therefore collaboration. In the sense that when an issue has a high number of comments i've typically been interested to find out what people are talking about

Sounds good, I've made a first pass here: #204
