### ISSUE TITLE
Seed file

### ISSUE THREAD

**Issue by samhstn** [dwyl/tudo#216]
Ensure the seed file is working.
Add back in how to the seed file [how to to run this file and what is for](https://hexdocs.pm/phoenix/seeding_data.html)
Add this information to the readme

**Comment by ZooeyMiller** [comment]
We're looking into running the seed file, but it seems we're getting permissions issues again (using the key that you @shouston3 gave us), and don't have the "HOOK_ENDPOINT", and can't quite see what it needs to be. Happy to update the README.md adding the relevant instructions when we've worked them out.

**Comment by finnhodgkin** [comment]
I'm guessing the hook_endpoint is the same one I used in the hook creation script last week (https://tudo-app.herokuapp.com/api/hooks). 

That portion of the seeding should already be done for all dwyl repos that @shouston3's key has access to, so for now we could comment that section out and concentrate on the database seeding. 

But yeah, it's error-ing due to bad permissions responses from the Github API so either we need to add some response handling or get a different key.

**Comment by ZooeyMiller** [comment]
The error turned out to be fixed by making it so that if `Poison.decode` is passed an empty string, we instead pass it `"{}".

I believe this is the solution @shouston3 and @finnhodgkin came up with last week when dealing with #211.

**Comment by finnhodgkin** [comment]
The live version is now seeded and there are instructions in the readme :+1:
