### ISSUE TITLE
Expanding as "Help Wanted" or working towards "tudo"

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/tudo#217]
During the call @finnhodgkin and I had with @Cleop and @shouston3 we talked about Help Wanted as an MVP, and the wider idea of the tudo app. 

For the kinds of issues that we raise and work on for today and tomorrow, should we be looking to expand the functionality of "Help Wanted" (for example ability to sort by priority, filter by repo, things like that) or look towards expanding it into "tudo"?

**Comment by iteles** [comment]
@ZooeyMiller Expanding the `help wanted` MVP to include some of the things that were captured but not implemented is our first port of call - displaying and filtering by labels, assignee, other filtering options etc would be great.

Very worth _capturing_ the wider conversation you had in issues however, so that that's not lost!

A reminder that in this repo we're trialling https://github.com/dwyl/labels/issues/73 , so please give it a go and see what you think.
