### ISSUE TITLE
Travis tests failing, local passing

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/tudo#224]
We've been banging our heads against travis for quite a while now. Our local tests are working absolutely fine (100% coverage, all tests passing), but on travis they fail with:

```
1) test GET / (Tudo.PageControllerTest)
     test/controllers/page_controller_test.exs:4
     ** (CaseClauseError) no case clause matching: %{"paginate" => %{}, "search" => %{}, "sort" => %{}}
     stacktrace:
       (tudo) web/controllers/page_controller.ex:10: Tudo.PageController.index/2
       (tudo) web/controllers/page_controller.ex:1: Tudo.PageController.action/2
       (tudo) web/controllers/page_controller.ex:1: Tudo.PageController.phoenix_controller_pipeline/2
       (tudo) lib/tudo/endpoint.ex:1: Tudo.Endpoint.instrument/4
       (tudo) lib/phoenix/router.ex:261: Tudo.Router.dispatch/2
       (tudo) web/router.ex:1: Tudo.Router.do_call/2
       (tudo) lib/tudo/endpoint.ex:1: Tudo.Endpoint.phoenix_pipeline/1
       (tudo) lib/tudo/endpoint.ex:1: Tudo.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/page_controller_test.exs:5: (test)
```

We can't see how the case could ever be called with the value that errors on travis side because the test uses a map with a key of rummage and value of `%{"paginate" => %{}, "search" => %{}, "sort" => %{}}`.

see #223

**Comment by ZooeyMiller** [comment]
After a few different thing (passing in different arguments, making the function call without brackets, or with brackets, changing elixir version) we're wondering if perhaps it could be that there is a problem when the tests are running on an unseeded database, so we're looking at trying that locally. 

It's slightly time consuming just because we have to push the code to see if it solves the travis problem. If the tests all pass properly with 100% coverage locally then I feel it must be some discrepancy between the local environment and the test environment.

EDIT: this idea came out of confusion, since the tests run on an unseeded test database, locallys and on travis.

**Comment by finnhodgkin** [comment]
The test database is empty so it's not that. I've now tried cloning the repo, creating new databases for both test and dev and then running the tests: everything still passes with 100% cov. 

It must be something to do with our travis setup. :woman_shrugging:

**Comment by finnhodgkin** [comment]
Well that took a very long time and in the end, as usual, was a super simple solution... We just swapped out the second case to a default with the params manually passed in.

Strange that elixir on travis requires a default when local doesn't but :woman_shrugging:
