### ISSUE TITLE
Allow people to turn off repo owners as a preference in mobile? 

### ISSUE THREAD

**Issue by jackpandas** [dwyl/tudo#94]
We are currently decided that the repo owner/name should be displayed to prevent confusion for people working on repos with the same name. For non-power users, should we allow them to see only repo names for a cleaner user interface?

**Comment by nelsonic** [comment]
@jackpandas makes sense. Could the UI be _enhanced_ when there is more than one repo with the same or similar name on the page...?

**Comment by jackpandas** [comment]
@nelsonic I think from the offline discussion, people wanted to be able to see the organisations as default in the main view

**Comment by nelsonic** [comment]
Oh...

**Comment by iteles** [comment]
@nelsonic The conversation that was had ended up with people wanting to quickly differentiate between issues that were part of one organisation vs another - the majority preference was to have [org name/repo name] as the standard in the main view.

The idea of opening this issue was to capture that the discussion was had and that we should be testing this in future as opinions beyond the room might differ :blush:

**Comment by Cleop** [comment]
Closing as currently only dealing with dwyl owned repos, can be reopened later when moving on to this.
